#!/usr/bin/env python3
"""
Generate one short DEM deck per static contact-model combination listed in
src/contact_model_whitelist.txt (SURFACE_DEFAULT only; superquadric needs an
SQ build, multicontact a different setup). Each deck packs 2 atom types in a
box with a primitive wall/gran floor using the same model, runs a few hundred
steps and dumps id x v f omega torque with %.17g, so that any last-bit change in
the per-contact kernels shows up in a byte comparison between two binaries.
usage: gen_decks.py <outdir>   -> writes <outdir>/<tag>/in.deck, prints tags
(LIGGGHTS modernization branch, kernel agent B5)
"""
import os, re, glob, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(ROOT, "src")

def ids(prefix):
    m = {}
    for f in glob.glob(os.path.join(SRC, prefix + "_model_*.h")):
        for line in open(f, errors="ignore"):
            mm = re.match(r"^%s_MODEL\((\w+),\s*([\w/]+),\s*(\d+)\)" % prefix.upper(), line)
            if mm: m[mm.group(1)] = mm.group(2)
    return m
NM, TM, CM, RM = ids("normal"), ids("tangential"), ids("cohesion"), ids("rolling")

# superset of material properties (2 atom types); unused ones are ignored
PROPS = """
fix  m1 all property/global youngsModulus peratomtype 5.e6 7.e6
fix  m2 all property/global poissonsRatio peratomtype 0.3 0.35
fix  m3 all property/global coefficientRestitution peratomtypepair 2 0.5 0.6 0.6 0.7
fix  m4 all property/global coefficientFriction peratomtypepair 2 0.5 0.4 0.4 0.3
fix  m5 all property/global characteristicVelocity scalar 0.5
fix  m6 all property/global cohesionEnergyDensity peratomtypepair 2 3000 3000 3000 3000
fix  m7 all property/global coefficientRollingFriction peratomtypepair 2 0.05 0.05 0.05 0.05
fix  m8 all property/global coefficientRollingViscousDamping peratomtypepair 2 0.1 0.1 0.1 0.1
fix  m9 all property/global coeffRollingStiffness peratomtypepair 2 0.5 0.5 0.5 0.5
fix  m10 all property/global kn peratomtypepair 2 2000 2000 2000 2000
fix  m11 all property/global kt peratomtypepair 2 1500 1500 1500 1500
fix  m12 all property/global gamman peratomtypepair 2 0.02 0.02 0.02 0.02
fix  m13 all property/global gammat peratomtypepair 2 0.01 0.01 0.01 0.01
fix  m14 all property/global surfaceLiquidContentInitial scalar 0.01
fix  m15 all property/global minSeparationDistanceRatio scalar 0.01
fix  m16 all property/global maxSeparationDistanceRatio scalar 1.1
fix  m17 all property/global fluidViscosity scalar 0.001
fix  m18 all property/global contactAngle peratomtype 0.5 0.3
fix  m19 all property/global surfaceTension scalar 0.072
fix  m20 all property/global workOfAdhesion peratomtypepair 2 0.05 0.05 0.05 0.05
fix  m21 all property/global FluidViscosity peratomtypepair 2 0.8 0.8 0.8 0.8
fix  m22 all property/global FrictionViscosity peratomtypepair 2 0.2 0.2 0.2 0.2
fix  m23 all property/global coeffFrictionStiffness peratomtypepair 2 0.3 0.3 0.3 0.3
fix  m24 all property/global coefficientMaxElasticStiffness peratomtypepair 2 2. 2. 2. 2.
fix  m25 all property/global coefficientAdhesionStiffness peratomtypepair 2 0.2 0.2 0.2 0.2
fix  m26 all property/global coefficientPlasticityDepth peratomtypepair 2 0.05 0.05 0.05 0.05
fix  m27 all property/global surfaceEnergy peratomtypepair 2 0.1 0.1 0.1 0.1
fix  m28 all property/global adhesionStress peratomtypepair 2 1000 1000 1000 1000
fix  m29 all property/global rollingStiffness scalar 2.0
fix  m30 all property/global overlapExponent scalar 1.5
fix  m31 all property/global LoadingStiffness peratomtypepair 2 2000 2000 2000 2000
fix  m32 all property/global UnloadingStiffness peratomtypepair 2 4000 4000 4000 4000
fix  m33 all property/global coefficientYieldRatio peratomtype 0.8 0.8
fix  m34 all property/global pullOffForce peratomtypepair 2 0.0 0.0 0.0 0.0
fix  m35 all property/global adhesionExponent scalar 1.5
@EXTRA@
"""

DECK = """# generated by tests/kernel/model_matrix/gen_decks.py: {combo}
atom_style    granular
atom_modify   map array
boundary      f f f
newton        off
communicate   single vel yes
units         si
region        domain block -0.0065 0.0065 -0.0065 0.0065 -0.0005 0.013 units box
create_box    2 domain
neighbor      0.0004 bin
neigh_modify  delay 0
timestep      2e-6
{props}
pair_style  gran {model}
pair_coeff  * *
fix  wall all wall/gran {model} primitive type 1 zplane 0.0
fix  wx1 all wall/gran {model} primitive type 1 xplane -0.006
fix  wx2 all wall/gran {model} primitive type 1 xplane 0.006
fix  wy1 all wall/gran {model} primitive type 1 yplane -0.006
fix  wy2 all wall/gran {model} primitive type 1 yplane 0.006
fix  wz2 all wall/gran {model} primitive type 1 zplane 0.0125
lattice       sc 0.00196
region        fill block -0.0045 0.0045 -0.0045 0.0045 0.0012 0.0105 units box
create_atoms  1 region fill
set type 1 type/fraction 2 0.5 4711
set atom * diameter 0.002 density 2500
fix gravi all gravity 200.0 vector 0.1 0.2 -1.0
fix integr all nve/sphere
thermo_style custom step atoms ke
thermo_modify format float %.17g
thermo 100
dump d all custom 1000 post/dump*.txt id x y z vx vy vz fx fy fz omegax omegay omegaz tqx tqy tqz
dump_modify d sort id format "%d{fmt}"
run 2000
"""

def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    extra_by = {}
    tags = []
    for line in open(os.path.join(SRC, "contact_model_whitelist.txt")):
        mm = re.match(r"GRAN_MODEL\((.*)\)", line.strip())
        if not mm: continue
        n, t, c, r, s = [x.strip() for x in mm.group(1).split(",")]
        if s != "SURFACE_DEFAULT": continue
        # thornton_ning + no_history loses atoms / segfaults in bin_atoms with
        # these generic parameters in the reference binary too (not a kernel
        # issue; reported in audit/fixes/phaseC/kernel/REPORT.md)
        if (n, t) == ("THORNTON_NING", "TANGENTIAL_NO_HISTORY"): continue
        model = "model %s tangential %s" % (NM[n], TM[t])
        if c != "COHESION_OFF": model += " cohesion %s" % CM[c]
        if r != "ROLLING_OFF": model += " rolling_friction %s" % RM[r]
        tag = "_".join(x.lower() for x in (n, t, c, r))
        extra = ""
        d = os.path.join(out, tag); os.makedirs(os.path.join(d, "post"), exist_ok=True)
        with open(os.path.join(d, "in.deck"), "w") as f:
            f.write(DECK.format(combo=line.strip(), props=PROPS.replace("@EXTRA@", extra),
                                model=model, fmt=" %.17g" * 15))
        tags.append(tag)
    print("\n".join(tags))
main()
